server:
  port: ${PORT:8080}
management:
  security:
    enabled: false
spring:
  application:
    name: soccer
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      default-binder: rabbit
      bindings:
        input:
          destination: goal
          group: group1
        output:
          destination: goal
          group: group1
